### ISSUE TITLE
How do I train my dataset from scratch

### ISSUE THREAD

**Issue by fuge92** [jprellberg/isbi2019cancer#3]
How do I train my dataset from scratch？

**Comment by jprellberg** [comment]
I updated the README with a more thorough description. It might be a little difficult to format the training data in the right way since I am not sure in what way the data was released after the challenge concluded.

**Comment by pk2005** [comment]
Hi, I have read your README and have formatted the data as per it, however the trainingset is empty. I believe something is different about the data naming or similar. Can you tell us what your original names of the files were? Currently we have data/fold_0/all/UID_1_1_1_all.bmp as example. Thanks!
